version: "3.3"

services:
  read-engine:
    image: qlikcore/engine:12.171.0
    restart: always
    command: >
      -S AcceptEULA=${ACCEPT_EULA}
      -S ValidateJsonWebTokens=2
      -S JsonWebTokenSecret=secret
      -S DocumentDirectory=/data
      -S SystemAllowRulePath=/rules/read_engine_rules_allow.txt
    ports:
      - "9176:9076"
    volumes:
      - ./data:/data
      - ./rules:/rules
  reload-engine:
    image: qlikcore/engine:12.171.0
    restart: always
    command: >
      -S AcceptEULA=${ACCEPT_EULA}
      -S ValidateJsonWebTokens=2
      -S JsonWebTokenSecret=secret
      -S DocumentDirectory=/data
      -S SystemAllowRulePath=/rules/reload_engine_rules_allow.txt
    ports:
      - "9276:9076"
    volumes:
      - ./data:/data
      - ./rules:/rules
